user_name = input("Введите имя пользователя")
print(f"Привет, {user_name}")
title1 = input("Введите заголовок 1")
print(f"Отлично! Ваш заголовок 1 {title1}")
title2 = input("Введите заголовок 2")
print(f"Отлично! Ваш заголовок 2 {title2}")
title3 = input("Введите заголовок 3")
print(f"Отлично! Ваш заголовок 3 {title3}")
content = input("Ваша заметка")
print(f"Так держать! Заметка {content} создана")
created_date = input("Введите дату начала")
issue_date = input("Введите дату окончания")
status = input("Введите статус заметки")
print(f"Статус вашей заметки изменен на {status}")
print(f"Имя пользователя: {user_name}")
print(f"Заголовок: {title1}")
print(f"Заголовок: {title2}")
print(f"Заголовок: {title3}")
print(f"Заметка: {content}")
print(f"Дата начала: {created_date[0:5]}")
print(f"Дата окончания: {issue_date[0:5]}")
print(f"Статус: {status}")
