user_name = input("Введите имя пользователя")
print(f"Привет, {user_name}")
title = input("Введите заголовок заметки")
print(f"Отлично! Ваш заголовок {title}")
content = input("Ваша заметка")
print(f"Так держать! Заметка {content} создана")
created_date = input("Введите дату начала")
issue_date = input("Введите дату окончания")
status = input("Введите статус заметки")
print(f"Статус вашей заметки изменен на {status}")
print(f"Имя пользователя: {user_name}")
print(f"Заголовок: {title}")
print(f"Заметка: {content}")
print(f"Дата начала: {created_date[0:5]}")
print(f"Дата окончания: {issue_date[0:5]}")
print(f"Статус: {status}")
